apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubevirt-hyperconverged
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: hco-operator
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.12.0
  name: kubevirt-hyperconverged-operator-metrics
  namespace: kubevirt-hyperconverged
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: hyperconverged-cluster-operator
  sessionAffinity: None
  type: ClusterIP
