apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-virtiofs-configmap
  name: vm-virtiofs-configmap
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-virtiofs-configmap
      annotations:
        descheduler.alpha.kubernetes.io/evict: "true"
    spec:
      domain:
        devices:
          filesystems:
            - name: cfg-virtiofs
              virtiofs: {}
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1
      - configMap:
          name: cfg-test-1
        name: cfg-virtiofs
      networks:
        - name: default
          pod: {}
  dataVolumeTemplates:
  - metadata:
      name: alpine-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rook-ceph-block
        volumeMode: Block
      source:
        http:
          url: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-37-1.7.iso
