apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-configmap
  name: vm-configmap
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-configmap
      annotations:
        descheduler.alpha.kubernetes.io/evict: "true"
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
            name: cfg-disk
            # set serial
            serial: CVLY623300HK240D
          - disk:
            name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 64M
      volumes:
      - dataVolume:
          name: alpine-dv
        name: datavolumedisk1
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            bootcmd:
              # mount the ConfigMap
              - "sudo mkdir /mnt/app-config"
              - "sudo mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
        name: cloudinitdisk
      - configMap:
          name: cfg-test-1
        name: cfg-disk
      networks:
        - name: default
          pod: {}
  dataVolumeTemplates:
  - metadata:
      name: alpine-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rook-ceph-block
        volumeMode: Block
      source:
        http:
          url: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-37-1.7.iso
