apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: fedora-vm-1
  name: fedora-secret
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-secret
        kubevirt.io/vm: fedora-secret
      annotations:
        descheduler.alpha.kubernetes.io/evict: "true"
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          filesystems:
            - name: app-secret-disk
              virtiofs: {}
            - name: app-secret-disk-2
              virtiofs: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
        resources:
          requests:
            memory: 1Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:36
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                expire: false
              password: password
              user: fedora
              bootcmd:
                - "mkdir /mnt/app-secret"
                - "mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-secret"
          name: cloudinitdisk
        - secret:
            secretName: app-secret
          name: app-secret-disk 
        - secret:
            secretName: app-secret-2
          name: app-secret-disk-2
